api_platform:
    title: "Symfony ESGI Association REST API"
    version: "1.0.0"
    mapping:
        paths: ["%kernel.project_dir%/src/Entity"]
    formats:
        json: ["application/json"]
        jsonld: ["application/ld+json"]
        html: ["text/html"]
        multipart: ["multipart/form-data"]
    patch_formats:
        json: ["application/merge-patch+json"]
    swagger:
        versions: [3]
    eager_loading:
        force_eager: false
    defaults:
        pagination_client_items_per_page: true
