vich_uploader:
    db_driver: orm

    mappings:
       users_images:
           uri_prefix: /media/users/
           upload_destination: '%kernel.project_dir%/public/media/users'
           delete_on_update: true
           delete_on_remove: true
           namer: 'Vich\UploaderBundle\Naming\UniqidNamer'
       associations_images:
           uri_prefix: /media/associations/
           upload_destination: '%kernel.project_dir%/public/media/associations'
           delete_on_update: true
           delete_on_remove: true
           namer: 'Vich\UploaderBundle\Naming\UniqidNamer'