version: '3.5'

services:
  node:
    image: node:18.2.0
    container_name: esgi-assos_node-ui
    working_dir: /var/www/
    env_file: ${envFile}
    environment:
      TZ: Europe/Paris
      DEBIAN_FRONTEND: noninteractive
    command: /bin/bash -c "yarn && yarn dev"
    ports:
      - 8080:8080
    volumes:
      - ./:/var/www/